# Generated by Django 6.0.3 on 2026-04-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_options_alter_interestingread_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='interestingread',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='interestingread',
            old_name='review',
            new_name='body',
        ),
        migrations.AddField(
            model_name='interestingread',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
