# Generated by Django 6.0.3 on 2026-04-08 11:13

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_options_alter_interestingread_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
