# Generated by Django 6.0.3 on 2026-04-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_biography_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='biography/'),
        ),
    ]
