# Generated by Django 6.0.3 on 2026-04-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_biography_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='image_caption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
