# Generated by Django 6.0.3 on 2026-04-08 12:15

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_biography_image_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='body_ru',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='biography',
            old_name='content',
            new_name='content_ru',
        ),
        migrations.RenameField(
            model_name='interestingread',
            old_name='body',
            new_name='body_ru',
        ),
        migrations.RenameField(
            model_name='interestingread',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RemoveField(
            model_name='biography',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='article',
            name='body_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='biography',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AddField(
            model_name='interestingread',
            name='body_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interestingread',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='interestingread',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
