# Generated by Django 6.0.3 on 2026-04-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_body_article_body_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title_ru']},
        ),
    ]
