# Generated by Django 6.0.3 on 2026-04-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_position',
            field=models.CharField(blank=True, choices=[('top', 'Top'), ('bottom', 'Bottom')], default='top', max_length=10),
        ),
    ]
