# Generated by Django 6.0.3 on 2026-04-10 21:32

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_article_image_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='body_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
