# Generated by Django 6.0.3 on 2026-04-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_visitorcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='family/')),
                ('caption_ru', models.CharField(blank=True, max_length=300)),
                ('caption_en', models.CharField(blank=True, max_length=300)),
                ('date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
