# Generated by Django 6.0.3 on 2026-04-19 13:05

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_familyphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestingread',
            name='title_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='interestingread',
            name='title_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
