# Generated by Django 6.0.3 on 2026-04-19 13:05

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_interestingread_title_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestingread',
            name='body_ru',
        ),
        migrations.AlterField(
            model_name='interestingread',
            name='body_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='interestingread',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='interestingread',
            name='title_ru',
            field=models.CharField(max_length=200),
        ),
    ]
