# Generated by Django 6.0.3 on 2026-04-19 13:08

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_interestingread_body_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestingread',
            name='body_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(default=''),
        ),
    ]
