# Generated by Django 6.0.3 on 2026-04-12 19:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
