# Generated by Django 6.0.3 on 2026-04-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_alter_guestentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='body',
            field=models.TextField(max_length=2000),
        ),
    ]
