# Generated by Django 6.0.3 on 2026-04-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0004_alter_guestentry_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='body',
            field=models.TextField(max_length=20000),
        ),
    ]
