# Generated by Django 6.0.3 on 2026-04-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0005_alter_guestentry_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingGuestEntry',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Entry',
                'verbose_name_plural': 'Pending Entries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('guestbook.guestentry',),
        ),
    ]
